/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.worldstudiosworld.init;

import net.neoforged.neoforge.transfer.fluid.BucketResourceHandler;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.*;

import net.mcreator.worldstudiosworld.item.inventory.TrashBagInventoryCapability;
import net.mcreator.worldstudiosworld.item.*;
import net.mcreator.worldstudiosworld.WorldstudiosWorldMod;

import java.util.function.Function;

@EventBusSubscriber
public class WorldstudiosWorldModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(WorldstudiosWorldMod.MODID);
	public static final DeferredItem<Item> COAL_PICKAXE;
	public static final DeferredItem<Item> ENDER_HELMET_HELMET;
	public static final DeferredItem<Item> ACID_ARMOR_HELMET;
	public static final DeferredItem<Item> ACID_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ACID_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ACID_ARMOR_BOOTS;
	public static final DeferredItem<Item> ACID_FLUID_BUCKET;
	public static final DeferredItem<Item> DINAMITE;
	public static final DeferredItem<Item> WASTE_BLOCK;
	public static final DeferredItem<Item> WASTE_STONE;
	public static final DeferredItem<Item> WASTE_LOG;
	public static final DeferredItem<Item> WASTE_LEAVES;
	public static final DeferredItem<Item> WASTE;
	public static final DeferredItem<Item> URAINIUM_CHUNK;
	public static final DeferredItem<Item> URAINIUM_PEICE;
	public static final DeferredItem<Item> URAINIUM_INGOT;
	public static final DeferredItem<Item> URAINIUM_BLADE;
	public static final DeferredItem<Item> URAINIUM_PICKAXE;
	public static final DeferredItem<Item> URAINIUM_SHIELD;
	public static final DeferredItem<Item> DIRT_ARMOR_HELMET;
	public static final DeferredItem<Item> DIRT_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DIRT_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DIRT_ARMOR_BOOTS;
	public static final DeferredItem<Item> GRAVITE;
	public static final DeferredItem<Item> ORACLE;
	public static final DeferredItem<Item> SEMITE;
	public static final DeferredItem<Item> FORGIUM_ORE;
	public static final DeferredItem<Item> FORGIUM;
	public static final DeferredItem<Item> FORGIUM_MULTITOOL;
	public static final DeferredItem<Item> MOLDELER;
	public static final DeferredItem<Item> CAPSULE;
	public static final DeferredItem<Item> CAPSULED_REDSTONE_BLOCK;
	public static final DeferredItem<Item> LONG_ZOMBIE_SPAWN_EGG;
	public static final DeferredItem<Item> TITAN_SPAWN_EGG;
	public static final DeferredItem<Item> TITAN_HEART;
	public static final DeferredItem<Item> TITAN_INGOT;
	public static final DeferredItem<Item> TITAN_ARMOR_ARMOR_HELMET;
	public static final DeferredItem<Item> TITAN_ARMOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TITAN_ARMOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TITAN_ARMOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> HEVORE;
	public static final DeferredItem<Item> TITAN_TOOL_PICKAXE;
	public static final DeferredItem<Item> TITAN_TOOL_AXE;
	public static final DeferredItem<Item> TITAN_TOOL_SWORD;
	public static final DeferredItem<Item> FAIRY_SPAWN_EGG;
	public static final DeferredItem<Item> BLOCK_OF_SPARKLES;
	public static final DeferredItem<Item> PROD_SPAWN_EGG;
	public static final DeferredItem<Item> PROD_MISSLE_ITEM;
	public static final DeferredItem<Item> SPARKLES;
	public static final DeferredItem<Item> FAIRY_HEART;
	public static final DeferredItem<Item> SPARKLE_PICKAXE;
	public static final DeferredItem<Item> SPARKLE_AXE;
	public static final DeferredItem<Item> SPARKLE_SWORD;
	public static final DeferredItem<Item> ENERGY_DETECTOR;
	public static final DeferredItem<Item> GYRULE_ORE;
	public static final DeferredItem<Item> GYRULE_CRYSTAL;
	public static final DeferredItem<Item> ANDOR_WOOD;
	public static final DeferredItem<Item> ANDOR_LOG;
	public static final DeferredItem<Item> ANDOR_PLANKS;
	public static final DeferredItem<Item> ANDOR_LEAVES;
	public static final DeferredItem<Item> ANDOR_STAIRS;
	public static final DeferredItem<Item> ANDOR_SLAB;
	public static final DeferredItem<Item> ANDOR_FENCE;
	public static final DeferredItem<Item> ANDOR_FENCE_GATE;
	public static final DeferredItem<Item> ANDOR_PRESSURE_PLATE;
	public static final DeferredItem<Item> ANDOR_BUTTON;
	public static final DeferredItem<Item> ANDOR_ARMOR_HELMET;
	public static final DeferredItem<Item> ANDOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ANDOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ANDOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> ANDOR_PICKAXE;
	public static final DeferredItem<Item> ANDOR_AXE;
	public static final DeferredItem<Item> ANDOR_SWORD;
	public static final DeferredItem<Item> ANDOR_SHOVEL;
	public static final DeferredItem<Item> ANDOR_HOE;
	public static final DeferredItem<Item> SUGAR_ENTITY_SPAWN_EGG;
	public static final DeferredItem<Item> FERTILIZED_SUGAR;
	public static final DeferredItem<Item> DIRT_TOOL_PICKAXE;
	public static final DeferredItem<Item> DIRT_TOOL_AXE;
	public static final DeferredItem<Item> DIRT_TOOL_SWORD;
	public static final DeferredItem<Item> DIRT_TOOL_SHOVEL;
	public static final DeferredItem<Item> DIRT_TOOL_HOE;
	public static final DeferredItem<Item> ANDESITE_PICKAXE;
	public static final DeferredItem<Item> ANDESITE_AXE;
	public static final DeferredItem<Item> ANDESITE_SWORD;
	public static final DeferredItem<Item> ANDESITE_SHOVEL;
	public static final DeferredItem<Item> ANDESITE_HOE;
	public static final DeferredItem<Item> GRANITE_ARMOR_HELMET;
	public static final DeferredItem<Item> GRANITE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> GRANITE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> GRANITE_ARMOR_BOOTS;
	public static final DeferredItem<Item> YELLOW_DIRT;
	public static final DeferredItem<Item> YELLOW_GRASS_BLOCK;
	public static final DeferredItem<Item> BLAZITE;
	public static final DeferredItem<Item> BLAZITE_ORE;
	public static final DeferredItem<Item> BLAZITE_BLOCK;
	public static final DeferredItem<Item> BLAZITE_PICKAXE;
	public static final DeferredItem<Item> BLAZITE_AXE;
	public static final DeferredItem<Item> BLAZITE_SWORD;
	public static final DeferredItem<Item> BLAZITE_SHOVEL;
	public static final DeferredItem<Item> BLAZITE_HOE;
	public static final DeferredItem<Item> BLAZITE_ARMOR_HELMET;
	public static final DeferredItem<Item> BLAZITE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BLAZITE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BLAZITE_ARMOR_BOOTS;
	public static final DeferredItem<Item> BRAIN;
	public static final DeferredItem<Item> BIRD_BRAIN_SPAWN_EGG;
	public static final DeferredItem<Item> STONE_ARMOR_HELMET;
	public static final DeferredItem<Item> STONE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> STONE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> STONE_ARMOR_BOOTS;
	public static final DeferredItem<Item> COOKIE;
	public static final DeferredItem<Item> SUGAR_COOKIE;
	public static final DeferredItem<Item> WOOL_ARMOR_HELMET;
	public static final DeferredItem<Item> WOOL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> WOOL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> WOOL_ARMOR_BOOTS;
	public static final DeferredItem<Item> ANDESITE_ARMOR_HELMET;
	public static final DeferredItem<Item> ANDESITE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ANDESITE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ANDESITE_ARMOR_BOOTS;
	public static final DeferredItem<Item> GRANITE_PICKAXE;
	public static final DeferredItem<Item> GRANITE_AXE;
	public static final DeferredItem<Item> GRANITE_SWORD;
	public static final DeferredItem<Item> GRANITE_SHOVEL;
	public static final DeferredItem<Item> GRANITE_HOE;
	public static final DeferredItem<Item> WOOL_PICKAXE;
	public static final DeferredItem<Item> WOOL_AXE;
	public static final DeferredItem<Item> WOOL_SWORD;
	public static final DeferredItem<Item> WOOL_SHOVEL;
	public static final DeferredItem<Item> WOOL_HOE;
	public static final DeferredItem<Item> BRAIN_ARMOR_ARMOR_HELMET;
	public static final DeferredItem<Item> BRAIN_ARMOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BRAIN_ARMOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BRAIN_ARMOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> HEROIC_DIAMOND;
	public static final DeferredItem<Item> TRASH_BAG;
	public static final DeferredItem<Item> DARK_BAT_SPAWN_EGG;
	public static final DeferredItem<Item> DARK_BAT_WING;
	public static final DeferredItem<Item> DARK_BAT_SHEILD;
	public static final DeferredItem<Item> THIEF_SPAWN_EGG;
	public static final DeferredItem<Item> APPLE_PIE;
	public static final DeferredItem<Item> GREEN_SAND;
	public static final DeferredItem<Item> GREEN_SANDSTONE;
	public static final DeferredItem<Item> SMOOTH_GREEN_SANDSTONE;
	public static final DeferredItem<Item> BRAIN_FOOD;
	public static final DeferredItem<Item> RADIANT_ZOMBIE_SPAWN_EGG;
	public static final DeferredItem<Item> FROZEN_GRAVITE;
	public static final DeferredItem<Item> NACOR_WOOD;
	public static final DeferredItem<Item> NACOR_LOG;
	public static final DeferredItem<Item> NACOR_PLANKS;
	public static final DeferredItem<Item> NACOR_LEAVES;
	public static final DeferredItem<Item> NACOR_STAIRS;
	public static final DeferredItem<Item> NACOR_SLAB;
	public static final DeferredItem<Item> NACOR_FENCE;
	public static final DeferredItem<Item> NACOR_FENCE_GATE;
	public static final DeferredItem<Item> NACOR_PRESSURE_PLATE;
	public static final DeferredItem<Item> NACOR_BUTTON;
	public static final DeferredItem<Item> NACOR_PICKAXE;
	public static final DeferredItem<Item> NACOR_AXE;
	public static final DeferredItem<Item> NACOR_SWORD;
	public static final DeferredItem<Item> NACOR_SHOVEL;
	public static final DeferredItem<Item> NACOR_HOE;
	public static final DeferredItem<Item> YETI_SPAWN_EGG;
	public static final DeferredItem<Item> SWORD_OF_THE_FROZEN_WARRIOR;
	public static final DeferredItem<Item> ICE_DRAGON_SPAWN_EGG;
	public static final DeferredItem<Item> ICE_DRAGON_ICEBALL;
	public static final DeferredItem<Item> YETI_HEART;
	public static final DeferredItem<Item> ICE_DRAGON_HEART;
	public static final DeferredItem<Item> ICEY_GRASS;
	public static final DeferredItem<Item> SKELETON_PICKAXE;
	public static final DeferredItem<Item> SKELETON_AXE;
	public static final DeferredItem<Item> SKELETON_SWORD;
	public static final DeferredItem<Item> SKELETON_SHOVEL;
	public static final DeferredItem<Item> SKELETON_HOE;
	public static final DeferredItem<Item> SKELETON_ARMOR_HELMET;
	public static final DeferredItem<Item> SKELETON_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SKELETON_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SKELETON_ARMOR_BOOTS;
	public static final DeferredItem<Item> IGNIGHTIUM_INGOT;
	public static final DeferredItem<Item> IGNIGHTIUM_ORE;
	public static final DeferredItem<Item> IGNIGHTIUM_BLOCK;
	public static final DeferredItem<Item> IGNIGHTIUM_PICKAXE;
	public static final DeferredItem<Item> IGNIGHTIUM_AXE;
	public static final DeferredItem<Item> IGNIGHTIUM_SWORD;
	public static final DeferredItem<Item> IGNIGHTIUM_SHOVEL;
	public static final DeferredItem<Item> IGNIGHTIUM_HOE;
	public static final DeferredItem<Item> IGNIGHTIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> IGNIGHTIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> IGNIGHTIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> IGNIGHTIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> BRAIN_FLUID_BUCKET;
	public static final DeferredItem<Item> COMMAND_BLOCK_ARMOR_HELMET;
	public static final DeferredItem<Item> COMMAND_BLOCK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> COMMAND_BLOCK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> COMMAND_BLOCK_ARMOR_BOOTS;
	public static final DeferredItem<Item> COMMAND_BLOCK_PICKAXE;
	public static final DeferredItem<Item> COMMAND_BLOCK_AXE;
	public static final DeferredItem<Item> COMMAND_BLOCK_SWORD;
	public static final DeferredItem<Item> COMMAND_BLOCK_SHOVEL;
	public static final DeferredItem<Item> COMMAND_BLOCK_HOE;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_ARMOR_HELMET;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_ARMOR_BOOTS;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_PICKAXE;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_AXE;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_SWORD;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_SHOVEL;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_HOE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_ARMOR_HELMET;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_ARMOR_BOOTS;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_PICKAXE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_AXE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_SWORD;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_SHOVEL;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_HOE;
	public static final DeferredItem<Item> MASTER_OF_THE_DARK_ARTS_SPAWN_EGG;
	public static final DeferredItem<Item> DARK_FLOWER;
	public static final DeferredItem<Item> ICE_PILLAR;
	public static final DeferredItem<Item> DARK_SPLATTER;
	public static final DeferredItem<Item> DARK_COOKIE;
	public static final DeferredItem<Item> DARK_PHANTOM_SPAWN_EGG;
	public static final DeferredItem<Item> DARK_PARTICLE_ITEM;
	public static final DeferredItem<Item> BRICK_ARMOR_HELMET;
	public static final DeferredItem<Item> BRICK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BRICK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BRICK_ARMOR_BOOTS;
	public static final DeferredItem<Item> RESIN_BRICK_ARMOR_HELMET;
	public static final DeferredItem<Item> RESIN_BRICK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> RESIN_BRICK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> RESIN_BRICK_ARMOR_BOOTS;
	public static final DeferredItem<Item> DEEPSLATE_BRICK_ARMOR_HELMET;
	public static final DeferredItem<Item> DEEPSLATE_BRICK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DEEPSLATE_BRICK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DEEPSLATE_BRICK_ARMOR_BOOTS;
	public static final DeferredItem<Item> IGNYITE;
	public static final DeferredItem<Item> STEEL;
	public static final DeferredItem<Item> STEEL_ARMOR_ARMOR_HELMET;
	public static final DeferredItem<Item> STEEL_ARMOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> STEEL_ARMOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> STEEL_ARMOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> STEEL_TOOL_PICKAXE;
	public static final DeferredItem<Item> STEEL_TOOL_AXE;
	public static final DeferredItem<Item> STEEL_TOOL_SWORD;
	public static final DeferredItem<Item> STEEL_TOOL_SHOVEL;
	public static final DeferredItem<Item> STEEL_TOOL_HOE;
	public static final DeferredItem<Item> CAPSTEEL;
	public static final DeferredItem<Item> REFINED_FLINT_AND_STEEL;
	public static final DeferredItem<Item> REBOUNDED_FIRE;
	public static final DeferredItem<Item> MOLTEN_METAL;
	public static final DeferredItem<Item> VERY_MOLTEN_METAL;
	public static final DeferredItem<Item> BLOCK_OF_FLINT;
	public static final DeferredItem<Item> WARTED_EMERALD;
	public static final DeferredItem<Item> WALKING_CHEST_SPAWN_EGG;
	public static final DeferredItem<Item> BRANITE;
	public static final DeferredItem<Item> BRANITE_ORE;
	public static final DeferredItem<Item> BRANITE_LUNGE;
	public static final DeferredItem<Item> BULL_SPAWN_EGG;
	public static final DeferredItem<Item> STONE_LUNGE;
	public static final DeferredItem<Item> AMETHESIUM_ORE;
	public static final DeferredItem<Item> AMETHESIUM_INGOT;
	public static final DeferredItem<Item> AMETHESIUM_PICKAXE;
	public static final DeferredItem<Item> AMETHESIUM_AXE;
	public static final DeferredItem<Item> AMETHESIUM_SWORD;
	public static final DeferredItem<Item> AMETHESIUM_SHOVEL;
	public static final DeferredItem<Item> AMETHESIUM_HOE;
	public static final DeferredItem<Item> AMETHESIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> AMETHESIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AMETHESIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AMETHESIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> AMETHESIUM_LUNGE;
	public static final DeferredItem<Item> CUBER_SPAWN_EGG;
	public static final DeferredItem<Item> CUBE_ESSENCE;
	public static final DeferredItem<Item> STEEL_BOAT;
	public static final DeferredItem<Item> CUTEPLANT;
	public static final DeferredItem<Item> CRAWLPING_SPAWN_EGG;
	public static final DeferredItem<Item> SAWPING_SPAWN_EGG;
	public static final DeferredItem<Item> SOULDUST_LOG;
	public static final DeferredItem<Item> SOULDUST_WOOD;
	public static final DeferredItem<Item> STRIPPED_SOULDUST_LOG;
	public static final DeferredItem<Item> STRIPPED_SOULDUST_WOOD;
	public static final DeferredItem<Item> SOULDUST_PLANKS;
	public static final DeferredItem<Item> SOULDUST_LEAVES;
	public static final DeferredItem<Item> SOULDUST_STAIRS;
	public static final DeferredItem<Item> SOULDUST_SLAB;
	public static final DeferredItem<Item> SOULDUST_FENCE;
	public static final DeferredItem<Item> SOULDUST_FENCE_GATE;
	public static final DeferredItem<Item> SOULDUST_DOOR;
	public static final DeferredItem<Item> SOULDUST_TRAPDOOR;
	public static final DeferredItem<Item> SOULDUST_PRESSURE_PLATE;
	public static final DeferredItem<Item> SOULDUST_BUTTON;
	public static final DeferredItem<Item> SOULDUST_SIGN;
	public static final DeferredItem<Item> SOULDUST_HANGING_SIGN;
	public static final DeferredItem<Item> SOULDUST_BOAT;
	public static final DeferredItem<Item> SOULDUST_CHEST_BOAT;
	public static final DeferredItem<Item> SOULDUST_PICKAXE;
	public static final DeferredItem<Item> SOULDUST_AXE;
	public static final DeferredItem<Item> SOULDUST_SWORD;
	public static final DeferredItem<Item> SOULDUST_SHOVEL;
	public static final DeferredItem<Item> SOULDUST_HOE;
	public static final DeferredItem<Item> GRAYSTONE;
	public static final DeferredItem<Item> SKIP;
	public static final DeferredItem<Item> DUAL_WEED;
	public static final DeferredItem<Item> DIRT_BOAT;
	public static final DeferredItem<Item> BREAKABLE_BEDROCK;
	public static final DeferredItem<Item> EYEFLOWER;
	public static final DeferredItem<Item> SOULDUST_GRAVITE;
	public static final DeferredItem<Item> OBSERVEER_SPAWN_EGG;
	public static final DeferredItem<Item> WOPPER_INGOT;
	public static final DeferredItem<Item> WOPPER_PICKAXE;
	public static final DeferredItem<Item> WOPPER_AXE;
	public static final DeferredItem<Item> WOPPER_SWORD;
	public static final DeferredItem<Item> WOPPER_SHOVEL;
	public static final DeferredItem<Item> WOPPER_HOE;
	public static final DeferredItem<Item> WOPPER_ARMOR_HELMET;
	public static final DeferredItem<Item> WOPPER_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> WOPPER_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> WOPPER_ARMOR_BOOTS;
	public static final DeferredItem<Item> DIRT_CHEST;
	public static final DeferredItem<Item> DARKENED_SAND;
	public static final DeferredItem<Item> GIRTREE_LOG;
	public static final DeferredItem<Item> GIRTREE_WOOD;
	public static final DeferredItem<Item> STRIPPED_GIRTREE_LOG;
	public static final DeferredItem<Item> STRIPPED_GIRTREE_WOOD;
	public static final DeferredItem<Item> GIRTREE_PLANKS;
	public static final DeferredItem<Item> GIRTREE_LEAVES;
	public static final DeferredItem<Item> GIRTREE_STAIRS;
	public static final DeferredItem<Item> GIRTREE_SLAB;
	public static final DeferredItem<Item> GIRTREE_FENCE;
	public static final DeferredItem<Item> GIRTREE_FENCE_GATE;
	public static final DeferredItem<Item> GIRTREE_DOOR;
	public static final DeferredItem<Item> GIRTREE_TRAPDOOR;
	public static final DeferredItem<Item> GIRTREE_PRESSURE_PLATE;
	public static final DeferredItem<Item> GIRTREE_BUTTON;
	public static final DeferredItem<Item> GIRTREE_SIGN;
	public static final DeferredItem<Item> GIRTREE_HANGING_SIGN;
	public static final DeferredItem<Item> GIRTREE_BOAT;
	public static final DeferredItem<Item> GIRTREE_CHEST_BOAT;
	public static final DeferredItem<Item> DIRTY_WATER_BUCKET;
	public static final DeferredItem<Item> SOGGY_DARKENED_SAND;
	public static final DeferredItem<Item> WANDERER_SPAWN_EGG;
	public static final DeferredItem<Item> DRIED_FLESH;
	public static final DeferredItem<Item> GIRSTONE;
	public static final DeferredItem<Item> IRON_UPGRADE_SMITHING_TEMPLATE;
	public static final DeferredItem<Item> TRAVERTINE;
	public static final DeferredItem<Item> TALLMOSS;
	public static final DeferredItem<Item> CHEAP_POINT;
	public static final DeferredItem<Item> PLANT_FOOD;
	public static final DeferredItem<Item> DIRT_SHIELD;
	public static final DeferredItem<Item> REPAIRER;
	public static final DeferredItem<Item> IRON_LUNGE;
	public static final DeferredItem<Item> DIAMOND_LUNGE;
	public static final DeferredItem<Item> NETHERITE_LUNGE;
	public static final DeferredItem<Item> URAINIUM_LUNGE;
	public static final DeferredItem<Item> TITAN_LUNGE;
	public static final DeferredItem<Item> SPARKLE_LUNGE;
	public static final DeferredItem<Item> BLAZITE_LUNGE;
	public static final DeferredItem<Item> WOOL_LUNGE;
	public static final DeferredItem<Item> IGNIGHTIUM_LUNGE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_LUNGE;
	public static final DeferredItem<Item> STEEL_LUNGE;
	public static final DeferredItem<Item> WOPPER_LUNGE;
	public static final DeferredItem<Item> STEEL_SYTHE;
	public static final DeferredItem<Item> TRASHERRACK;
	public static final DeferredItem<Item> TRASH_BRUTE_SPAWN_EGG;
	public static final DeferredItem<Item> END_NEZIUM_ORE;
	public static final DeferredItem<Item> RAW_NEZIUM;
	public static final DeferredItem<Item> NEZIUM_INGOT;
	public static final DeferredItem<Item> NEZIUM_PICKAXE;
	public static final DeferredItem<Item> NEZIUM_AXE;
	public static final DeferredItem<Item> NEZIUM_SWORD;
	public static final DeferredItem<Item> NEZIUM_SHOVEL;
	public static final DeferredItem<Item> NEZIUM_HOE;
	public static final DeferredItem<Item> NEZIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> NEZIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> NEZIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> NEZIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> NEZIUM_LUNGE;
	static {
		COAL_PICKAXE = register("coal_pickaxe", CoalPickaxeItem::new);
		ENDER_HELMET_HELMET = register("ender_helmet_helmet", EnderHelmetItem.Helmet::new);
		ACID_ARMOR_HELMET = register("acid_armor_helmet", AcidArmorItem.Helmet::new);
		ACID_ARMOR_CHESTPLATE = register("acid_armor_chestplate", AcidArmorItem.Chestplate::new);
		ACID_ARMOR_LEGGINGS = register("acid_armor_leggings", AcidArmorItem.Leggings::new);
		ACID_ARMOR_BOOTS = register("acid_armor_boots", AcidArmorItem.Boots::new);
		ACID_FLUID_BUCKET = register("acid_fluid_bucket", AcidFluidItem::new);
		DINAMITE = register("dinamite", DinamiteItem::new);
		WASTE_BLOCK = block(WorldstudiosWorldModBlocks.WASTE_BLOCK);
		WASTE_STONE = block(WorldstudiosWorldModBlocks.WASTE_STONE);
		WASTE_LOG = block(WorldstudiosWorldModBlocks.WASTE_LOG);
		WASTE_LEAVES = block(WorldstudiosWorldModBlocks.WASTE_LEAVES);
		WASTE = register("waste", WasteItem::new);
		URAINIUM_CHUNK = block(WorldstudiosWorldModBlocks.URAINIUM_CHUNK);
		URAINIUM_PEICE = register("urainium_peice", UrainiumPeiceItem::new);
		URAINIUM_INGOT = register("urainium_ingot", UrainiumIngotItem::new);
		URAINIUM_BLADE = register("urainium_blade", UrainiumBladeItem::new);
		URAINIUM_PICKAXE = register("urainium_pickaxe", UrainiumPickaxeItem::new);
		URAINIUM_SHIELD = register("urainium_shield", UrainiumShieldItem::new);
		DIRT_ARMOR_HELMET = register("dirt_armor_helmet", DirtArmorItem.Helmet::new);
		DIRT_ARMOR_CHESTPLATE = register("dirt_armor_chestplate", DirtArmorItem.Chestplate::new);
		DIRT_ARMOR_LEGGINGS = register("dirt_armor_leggings", DirtArmorItem.Leggings::new);
		DIRT_ARMOR_BOOTS = register("dirt_armor_boots", DirtArmorItem.Boots::new);
		GRAVITE = block(WorldstudiosWorldModBlocks.GRAVITE);
		ORACLE = register("oracle", OracleItem::new);
		SEMITE = block(WorldstudiosWorldModBlocks.SEMITE);
		FORGIUM_ORE = block(WorldstudiosWorldModBlocks.FORGIUM_ORE);
		FORGIUM = register("forgium", ForgiumItem::new);
		FORGIUM_MULTITOOL = register("forgium_multitool", ForgiumMultitoolItem::new);
		MOLDELER = block(WorldstudiosWorldModBlocks.MOLDELER);
		CAPSULE = block(WorldstudiosWorldModBlocks.CAPSULE);
		CAPSULED_REDSTONE_BLOCK = block(WorldstudiosWorldModBlocks.CAPSULED_REDSTONE_BLOCK);
		LONG_ZOMBIE_SPAWN_EGG = register("long_zombie_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.LONG_ZOMBIE.get())));
		TITAN_SPAWN_EGG = register("titan_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.TITAN.get())));
		TITAN_HEART = register("titan_heart", TitanHeartItem::new);
		TITAN_INGOT = register("titan_ingot", TitanIngotItem::new);
		TITAN_ARMOR_ARMOR_HELMET = register("titan_armor_armor_helmet", TitanArmorArmorItem.Helmet::new);
		TITAN_ARMOR_ARMOR_CHESTPLATE = register("titan_armor_armor_chestplate", TitanArmorArmorItem.Chestplate::new);
		TITAN_ARMOR_ARMOR_LEGGINGS = register("titan_armor_armor_leggings", TitanArmorArmorItem.Leggings::new);
		TITAN_ARMOR_ARMOR_BOOTS = register("titan_armor_armor_boots", TitanArmorArmorItem.Boots::new);
		HEVORE = block(WorldstudiosWorldModBlocks.HEVORE);
		TITAN_TOOL_PICKAXE = register("titan_tool_pickaxe", TitanToolPickaxeItem::new);
		TITAN_TOOL_AXE = register("titan_tool_axe", TitanToolAxeItem::new);
		TITAN_TOOL_SWORD = register("titan_tool_sword", TitanToolSwordItem::new);
		FAIRY_SPAWN_EGG = register("fairy_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.FAIRY.get())));
		BLOCK_OF_SPARKLES = block(WorldstudiosWorldModBlocks.BLOCK_OF_SPARKLES);
		PROD_SPAWN_EGG = register("prod_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.PROD.get())));
		PROD_MISSLE_ITEM = register("prod_missle_item", ProdMissleItemItem::new);
		SPARKLES = register("sparkles", SparklesItem::new);
		FAIRY_HEART = register("fairy_heart", FairyHeartItem::new);
		SPARKLE_PICKAXE = register("sparkle_pickaxe", SparklePickaxeItem::new);
		SPARKLE_AXE = register("sparkle_axe", SparkleAxeItem::new);
		SPARKLE_SWORD = register("sparkle_sword", SparkleSwordItem::new);
		ENERGY_DETECTOR = register("energy_detector", EnergyDetectorItem::new);
		GYRULE_ORE = block(WorldstudiosWorldModBlocks.GYRULE_ORE);
		GYRULE_CRYSTAL = register("gyrule_crystal", GyruleCrystalItem::new);
		ANDOR_WOOD = block(WorldstudiosWorldModBlocks.ANDOR_WOOD);
		ANDOR_LOG = block(WorldstudiosWorldModBlocks.ANDOR_LOG);
		ANDOR_PLANKS = block(WorldstudiosWorldModBlocks.ANDOR_PLANKS);
		ANDOR_LEAVES = block(WorldstudiosWorldModBlocks.ANDOR_LEAVES);
		ANDOR_STAIRS = block(WorldstudiosWorldModBlocks.ANDOR_STAIRS);
		ANDOR_SLAB = block(WorldstudiosWorldModBlocks.ANDOR_SLAB);
		ANDOR_FENCE = block(WorldstudiosWorldModBlocks.ANDOR_FENCE);
		ANDOR_FENCE_GATE = block(WorldstudiosWorldModBlocks.ANDOR_FENCE_GATE);
		ANDOR_PRESSURE_PLATE = block(WorldstudiosWorldModBlocks.ANDOR_PRESSURE_PLATE);
		ANDOR_BUTTON = block(WorldstudiosWorldModBlocks.ANDOR_BUTTON);
		ANDOR_ARMOR_HELMET = register("andor_armor_helmet", AndorArmorItem.Helmet::new);
		ANDOR_ARMOR_CHESTPLATE = register("andor_armor_chestplate", AndorArmorItem.Chestplate::new);
		ANDOR_ARMOR_LEGGINGS = register("andor_armor_leggings", AndorArmorItem.Leggings::new);
		ANDOR_ARMOR_BOOTS = register("andor_armor_boots", AndorArmorItem.Boots::new);
		ANDOR_PICKAXE = register("andor_pickaxe", AndorPickaxeItem::new);
		ANDOR_AXE = register("andor_axe", AndorAxeItem::new);
		ANDOR_SWORD = register("andor_sword", AndorSwordItem::new);
		ANDOR_SHOVEL = register("andor_shovel", AndorShovelItem::new);
		ANDOR_HOE = register("andor_hoe", AndorHoeItem::new);
		SUGAR_ENTITY_SPAWN_EGG = register("sugar_entity_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.SUGAR_ENTITY.get())));
		FERTILIZED_SUGAR = register("fertilized_sugar", FertilizedSugarItem::new);
		DIRT_TOOL_PICKAXE = register("dirt_tool_pickaxe", DirtToolPickaxeItem::new);
		DIRT_TOOL_AXE = register("dirt_tool_axe", DirtToolAxeItem::new);
		DIRT_TOOL_SWORD = register("dirt_tool_sword", DirtToolSwordItem::new);
		DIRT_TOOL_SHOVEL = register("dirt_tool_shovel", DirtToolShovelItem::new);
		DIRT_TOOL_HOE = register("dirt_tool_hoe", DirtToolHoeItem::new);
		ANDESITE_PICKAXE = register("andesite_pickaxe", AndesitePickaxeItem::new);
		ANDESITE_AXE = register("andesite_axe", AndesiteAxeItem::new);
		ANDESITE_SWORD = register("andesite_sword", AndesiteSwordItem::new);
		ANDESITE_SHOVEL = register("andesite_shovel", AndesiteShovelItem::new);
		ANDESITE_HOE = register("andesite_hoe", AndesiteHoeItem::new);
		GRANITE_ARMOR_HELMET = register("granite_armor_helmet", GraniteArmorItem.Helmet::new);
		GRANITE_ARMOR_CHESTPLATE = register("granite_armor_chestplate", GraniteArmorItem.Chestplate::new);
		GRANITE_ARMOR_LEGGINGS = register("granite_armor_leggings", GraniteArmorItem.Leggings::new);
		GRANITE_ARMOR_BOOTS = register("granite_armor_boots", GraniteArmorItem.Boots::new);
		YELLOW_DIRT = block(WorldstudiosWorldModBlocks.YELLOW_DIRT);
		YELLOW_GRASS_BLOCK = block(WorldstudiosWorldModBlocks.YELLOW_GRASS_BLOCK);
		BLAZITE = register("blazite", BlaziteItem::new);
		BLAZITE_ORE = block(WorldstudiosWorldModBlocks.BLAZITE_ORE);
		BLAZITE_BLOCK = block(WorldstudiosWorldModBlocks.BLAZITE_BLOCK);
		BLAZITE_PICKAXE = register("blazite_pickaxe", BlazitePickaxeItem::new);
		BLAZITE_AXE = register("blazite_axe", BlaziteAxeItem::new);
		BLAZITE_SWORD = register("blazite_sword", BlaziteSwordItem::new);
		BLAZITE_SHOVEL = register("blazite_shovel", BlaziteShovelItem::new);
		BLAZITE_HOE = register("blazite_hoe", BlaziteHoeItem::new);
		BLAZITE_ARMOR_HELMET = register("blazite_armor_helmet", BlaziteArmorItem.Helmet::new);
		BLAZITE_ARMOR_CHESTPLATE = register("blazite_armor_chestplate", BlaziteArmorItem.Chestplate::new);
		BLAZITE_ARMOR_LEGGINGS = register("blazite_armor_leggings", BlaziteArmorItem.Leggings::new);
		BLAZITE_ARMOR_BOOTS = register("blazite_armor_boots", BlaziteArmorItem.Boots::new);
		BRAIN = block(WorldstudiosWorldModBlocks.BRAIN);
		BIRD_BRAIN_SPAWN_EGG = register("bird_brain_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.BIRD_BRAIN.get())));
		STONE_ARMOR_HELMET = register("stone_armor_helmet", StoneArmorItem.Helmet::new);
		STONE_ARMOR_CHESTPLATE = register("stone_armor_chestplate", StoneArmorItem.Chestplate::new);
		STONE_ARMOR_LEGGINGS = register("stone_armor_leggings", StoneArmorItem.Leggings::new);
		STONE_ARMOR_BOOTS = register("stone_armor_boots", StoneArmorItem.Boots::new);
		COOKIE = register("cookie", CookieItem::new);
		SUGAR_COOKIE = register("sugar_cookie", SugarCookieItem::new);
		WOOL_ARMOR_HELMET = register("wool_armor_helmet", WoolArmorItem.Helmet::new);
		WOOL_ARMOR_CHESTPLATE = register("wool_armor_chestplate", WoolArmorItem.Chestplate::new);
		WOOL_ARMOR_LEGGINGS = register("wool_armor_leggings", WoolArmorItem.Leggings::new);
		WOOL_ARMOR_BOOTS = register("wool_armor_boots", WoolArmorItem.Boots::new);
		ANDESITE_ARMOR_HELMET = register("andesite_armor_helmet", AndesiteArmorItem.Helmet::new);
		ANDESITE_ARMOR_CHESTPLATE = register("andesite_armor_chestplate", AndesiteArmorItem.Chestplate::new);
		ANDESITE_ARMOR_LEGGINGS = register("andesite_armor_leggings", AndesiteArmorItem.Leggings::new);
		ANDESITE_ARMOR_BOOTS = register("andesite_armor_boots", AndesiteArmorItem.Boots::new);
		GRANITE_PICKAXE = register("granite_pickaxe", GranitePickaxeItem::new);
		GRANITE_AXE = register("granite_axe", GraniteAxeItem::new);
		GRANITE_SWORD = register("granite_sword", GraniteSwordItem::new);
		GRANITE_SHOVEL = register("granite_shovel", GraniteShovelItem::new);
		GRANITE_HOE = register("granite_hoe", GraniteHoeItem::new);
		WOOL_PICKAXE = register("wool_pickaxe", WoolPickaxeItem::new);
		WOOL_AXE = register("wool_axe", WoolAxeItem::new);
		WOOL_SWORD = register("wool_sword", WoolSwordItem::new);
		WOOL_SHOVEL = register("wool_shovel", WoolShovelItem::new);
		WOOL_HOE = register("wool_hoe", WoolHoeItem::new);
		BRAIN_ARMOR_ARMOR_HELMET = register("brain_armor_armor_helmet", BrainArmorArmorItem.Helmet::new);
		BRAIN_ARMOR_ARMOR_CHESTPLATE = register("brain_armor_armor_chestplate", BrainArmorArmorItem.Chestplate::new);
		BRAIN_ARMOR_ARMOR_LEGGINGS = register("brain_armor_armor_leggings", BrainArmorArmorItem.Leggings::new);
		BRAIN_ARMOR_ARMOR_BOOTS = register("brain_armor_armor_boots", BrainArmorArmorItem.Boots::new);
		HEROIC_DIAMOND = register("heroic_diamond", HeroicDiamondItem::new);
		TRASH_BAG = register("trash_bag", TrashBagItem::new);
		DARK_BAT_SPAWN_EGG = register("dark_bat_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.DARK_BAT.get())));
		DARK_BAT_WING = register("dark_bat_wing", DarkBatWingItem::new);
		DARK_BAT_SHEILD = register("dark_bat_sheild", DarkBatSheildItem::new);
		THIEF_SPAWN_EGG = register("thief_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.THIEF.get())));
		APPLE_PIE = register("apple_pie", ApplePieItem::new);
		GREEN_SAND = block(WorldstudiosWorldModBlocks.GREEN_SAND);
		GREEN_SANDSTONE = block(WorldstudiosWorldModBlocks.GREEN_SANDSTONE);
		SMOOTH_GREEN_SANDSTONE = block(WorldstudiosWorldModBlocks.SMOOTH_GREEN_SANDSTONE);
		BRAIN_FOOD = register("brain_food", BrainFoodItem::new);
		RADIANT_ZOMBIE_SPAWN_EGG = register("radiant_zombie_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.RADIANT_ZOMBIE.get())));
		FROZEN_GRAVITE = block(WorldstudiosWorldModBlocks.FROZEN_GRAVITE);
		NACOR_WOOD = block(WorldstudiosWorldModBlocks.NACOR_WOOD);
		NACOR_LOG = block(WorldstudiosWorldModBlocks.NACOR_LOG);
		NACOR_PLANKS = block(WorldstudiosWorldModBlocks.NACOR_PLANKS);
		NACOR_LEAVES = block(WorldstudiosWorldModBlocks.NACOR_LEAVES);
		NACOR_STAIRS = block(WorldstudiosWorldModBlocks.NACOR_STAIRS);
		NACOR_SLAB = block(WorldstudiosWorldModBlocks.NACOR_SLAB);
		NACOR_FENCE = block(WorldstudiosWorldModBlocks.NACOR_FENCE);
		NACOR_FENCE_GATE = block(WorldstudiosWorldModBlocks.NACOR_FENCE_GATE);
		NACOR_PRESSURE_PLATE = block(WorldstudiosWorldModBlocks.NACOR_PRESSURE_PLATE);
		NACOR_BUTTON = block(WorldstudiosWorldModBlocks.NACOR_BUTTON);
		NACOR_PICKAXE = register("nacor_pickaxe", NacorPickaxeItem::new);
		NACOR_AXE = register("nacor_axe", NacorAxeItem::new);
		NACOR_SWORD = register("nacor_sword", NacorSwordItem::new);
		NACOR_SHOVEL = register("nacor_shovel", NacorShovelItem::new);
		NACOR_HOE = register("nacor_hoe", NacorHoeItem::new);
		YETI_SPAWN_EGG = register("yeti_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.YETI.get())));
		SWORD_OF_THE_FROZEN_WARRIOR = register("sword_of_the_frozen_warrior", SwordOfTheFrozenWarriorItem::new);
		ICE_DRAGON_SPAWN_EGG = register("ice_dragon_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.ICE_DRAGON.get())));
		ICE_DRAGON_ICEBALL = register("ice_dragon_iceball", IceDragonIceballItem::new);
		YETI_HEART = register("yeti_heart", YetiHeartItem::new);
		ICE_DRAGON_HEART = register("ice_dragon_heart", IceDragonHeartItem::new);
		ICEY_GRASS = block(WorldstudiosWorldModBlocks.ICEY_GRASS);
		SKELETON_PICKAXE = register("skeleton_pickaxe", SkeletonPickaxeItem::new);
		SKELETON_AXE = register("skeleton_axe", SkeletonAxeItem::new);
		SKELETON_SWORD = register("skeleton_sword", SkeletonSwordItem::new);
		SKELETON_SHOVEL = register("skeleton_shovel", SkeletonShovelItem::new);
		SKELETON_HOE = register("skeleton_hoe", SkeletonHoeItem::new);
		SKELETON_ARMOR_HELMET = register("skeleton_armor_helmet", SkeletonArmorItem.Helmet::new);
		SKELETON_ARMOR_CHESTPLATE = register("skeleton_armor_chestplate", SkeletonArmorItem.Chestplate::new);
		SKELETON_ARMOR_LEGGINGS = register("skeleton_armor_leggings", SkeletonArmorItem.Leggings::new);
		SKELETON_ARMOR_BOOTS = register("skeleton_armor_boots", SkeletonArmorItem.Boots::new);
		IGNIGHTIUM_INGOT = register("ignightium_ingot", IgnightiumIngotItem::new);
		IGNIGHTIUM_ORE = block(WorldstudiosWorldModBlocks.IGNIGHTIUM_ORE);
		IGNIGHTIUM_BLOCK = block(WorldstudiosWorldModBlocks.IGNIGHTIUM_BLOCK);
		IGNIGHTIUM_PICKAXE = register("ignightium_pickaxe", IgnightiumPickaxeItem::new);
		IGNIGHTIUM_AXE = register("ignightium_axe", IgnightiumAxeItem::new);
		IGNIGHTIUM_SWORD = register("ignightium_sword", IgnightiumSwordItem::new);
		IGNIGHTIUM_SHOVEL = register("ignightium_shovel", IgnightiumShovelItem::new);
		IGNIGHTIUM_HOE = register("ignightium_hoe", IgnightiumHoeItem::new);
		IGNIGHTIUM_ARMOR_HELMET = register("ignightium_armor_helmet", IgnightiumArmorItem.Helmet::new);
		IGNIGHTIUM_ARMOR_CHESTPLATE = register("ignightium_armor_chestplate", IgnightiumArmorItem.Chestplate::new);
		IGNIGHTIUM_ARMOR_LEGGINGS = register("ignightium_armor_leggings", IgnightiumArmorItem.Leggings::new);
		IGNIGHTIUM_ARMOR_BOOTS = register("ignightium_armor_boots", IgnightiumArmorItem.Boots::new);
		BRAIN_FLUID_BUCKET = register("brain_fluid_bucket", BrainFluidItem::new);
		COMMAND_BLOCK_ARMOR_HELMET = register("command_block_armor_helmet", CommandBlockArmorItem.Helmet::new);
		COMMAND_BLOCK_ARMOR_CHESTPLATE = register("command_block_armor_chestplate", CommandBlockArmorItem.Chestplate::new);
		COMMAND_BLOCK_ARMOR_LEGGINGS = register("command_block_armor_leggings", CommandBlockArmorItem.Leggings::new);
		COMMAND_BLOCK_ARMOR_BOOTS = register("command_block_armor_boots", CommandBlockArmorItem.Boots::new);
		COMMAND_BLOCK_PICKAXE = register("command_block_pickaxe", CommandBlockPickaxeItem::new);
		COMMAND_BLOCK_AXE = register("command_block_axe", CommandBlockAxeItem::new);
		COMMAND_BLOCK_SWORD = register("command_block_sword", CommandBlockSwordItem::new);
		COMMAND_BLOCK_SHOVEL = register("command_block_shovel", CommandBlockShovelItem::new);
		COMMAND_BLOCK_HOE = register("command_block_hoe", CommandBlockHoeItem::new);
		CHAIN_COMMAND_BLOCK_ARMOR_HELMET = register("chain_command_block_armor_helmet", ChainCommandBlockArmorItem.Helmet::new);
		CHAIN_COMMAND_BLOCK_ARMOR_CHESTPLATE = register("chain_command_block_armor_chestplate", ChainCommandBlockArmorItem.Chestplate::new);
		CHAIN_COMMAND_BLOCK_ARMOR_LEGGINGS = register("chain_command_block_armor_leggings", ChainCommandBlockArmorItem.Leggings::new);
		CHAIN_COMMAND_BLOCK_ARMOR_BOOTS = register("chain_command_block_armor_boots", ChainCommandBlockArmorItem.Boots::new);
		CHAIN_COMMAND_BLOCK_PICKAXE = register("chain_command_block_pickaxe", ChainCommandBlockPickaxeItem::new);
		CHAIN_COMMAND_BLOCK_AXE = register("chain_command_block_axe", ChainCommandBlockAxeItem::new);
		CHAIN_COMMAND_BLOCK_SWORD = register("chain_command_block_sword", ChainCommandBlockSwordItem::new);
		CHAIN_COMMAND_BLOCK_SHOVEL = register("chain_command_block_shovel", ChainCommandBlockShovelItem::new);
		CHAIN_COMMAND_BLOCK_HOE = register("chain_command_block_hoe", ChainCommandBlockHoeItem::new);
		REPEATING_COMMAND_BLOCK_ARMOR_HELMET = register("repeating_command_block_armor_helmet", RepeatingCommandBlockArmorItem.Helmet::new);
		REPEATING_COMMAND_BLOCK_ARMOR_CHESTPLATE = register("repeating_command_block_armor_chestplate", RepeatingCommandBlockArmorItem.Chestplate::new);
		REPEATING_COMMAND_BLOCK_ARMOR_LEGGINGS = register("repeating_command_block_armor_leggings", RepeatingCommandBlockArmorItem.Leggings::new);
		REPEATING_COMMAND_BLOCK_ARMOR_BOOTS = register("repeating_command_block_armor_boots", RepeatingCommandBlockArmorItem.Boots::new);
		REPEATING_COMMAND_BLOCK_PICKAXE = register("repeating_command_block_pickaxe", RepeatingCommandBlockPickaxeItem::new);
		REPEATING_COMMAND_BLOCK_AXE = register("repeating_command_block_axe", RepeatingCommandBlockAxeItem::new);
		REPEATING_COMMAND_BLOCK_SWORD = register("repeating_command_block_sword", RepeatingCommandBlockSwordItem::new);
		REPEATING_COMMAND_BLOCK_SHOVEL = register("repeating_command_block_shovel", RepeatingCommandBlockShovelItem::new);
		REPEATING_COMMAND_BLOCK_HOE = register("repeating_command_block_hoe", RepeatingCommandBlockHoeItem::new);
		MASTER_OF_THE_DARK_ARTS_SPAWN_EGG = register("master_of_the_dark_arts_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.MASTER_OF_THE_DARK_ARTS.get())));
		DARK_FLOWER = block(WorldstudiosWorldModBlocks.DARK_FLOWER);
		ICE_PILLAR = block(WorldstudiosWorldModBlocks.ICE_PILLAR);
		DARK_SPLATTER = register("dark_splatter", DarkSplatterItem::new);
		DARK_COOKIE = register("dark_cookie", DarkCookieItem::new);
		DARK_PHANTOM_SPAWN_EGG = register("dark_phantom_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.DARK_PHANTOM.get())));
		DARK_PARTICLE_ITEM = register("dark_particle_item", DarkParticleItemItem::new);
		BRICK_ARMOR_HELMET = register("brick_armor_helmet", BrickArmorItem.Helmet::new);
		BRICK_ARMOR_CHESTPLATE = register("brick_armor_chestplate", BrickArmorItem.Chestplate::new);
		BRICK_ARMOR_LEGGINGS = register("brick_armor_leggings", BrickArmorItem.Leggings::new);
		BRICK_ARMOR_BOOTS = register("brick_armor_boots", BrickArmorItem.Boots::new);
		RESIN_BRICK_ARMOR_HELMET = register("resin_brick_armor_helmet", ResinBrickArmorItem.Helmet::new);
		RESIN_BRICK_ARMOR_CHESTPLATE = register("resin_brick_armor_chestplate", ResinBrickArmorItem.Chestplate::new);
		RESIN_BRICK_ARMOR_LEGGINGS = register("resin_brick_armor_leggings", ResinBrickArmorItem.Leggings::new);
		RESIN_BRICK_ARMOR_BOOTS = register("resin_brick_armor_boots", ResinBrickArmorItem.Boots::new);
		DEEPSLATE_BRICK_ARMOR_HELMET = register("deepslate_brick_armor_helmet", DeepslateBrickArmorItem.Helmet::new);
		DEEPSLATE_BRICK_ARMOR_CHESTPLATE = register("deepslate_brick_armor_chestplate", DeepslateBrickArmorItem.Chestplate::new);
		DEEPSLATE_BRICK_ARMOR_LEGGINGS = register("deepslate_brick_armor_leggings", DeepslateBrickArmorItem.Leggings::new);
		DEEPSLATE_BRICK_ARMOR_BOOTS = register("deepslate_brick_armor_boots", DeepslateBrickArmorItem.Boots::new);
		IGNYITE = block(WorldstudiosWorldModBlocks.IGNYITE);
		STEEL = register("steel", SteelItem::new);
		STEEL_ARMOR_ARMOR_HELMET = register("steel_armor_armor_helmet", SteelArmorArmorItem.Helmet::new);
		STEEL_ARMOR_ARMOR_CHESTPLATE = register("steel_armor_armor_chestplate", SteelArmorArmorItem.Chestplate::new);
		STEEL_ARMOR_ARMOR_LEGGINGS = register("steel_armor_armor_leggings", SteelArmorArmorItem.Leggings::new);
		STEEL_ARMOR_ARMOR_BOOTS = register("steel_armor_armor_boots", SteelArmorArmorItem.Boots::new);
		STEEL_TOOL_PICKAXE = register("steel_tool_pickaxe", SteelToolPickaxeItem::new);
		STEEL_TOOL_AXE = register("steel_tool_axe", SteelToolAxeItem::new);
		STEEL_TOOL_SWORD = register("steel_tool_sword", SteelToolSwordItem::new);
		STEEL_TOOL_SHOVEL = register("steel_tool_shovel", SteelToolShovelItem::new);
		STEEL_TOOL_HOE = register("steel_tool_hoe", SteelToolHoeItem::new);
		CAPSTEEL = register("capsteel", CapsteelItem::new);
		REFINED_FLINT_AND_STEEL = register("refined_flint_and_steel", RefinedFlintAndSteelItem::new);
		REBOUNDED_FIRE = block(WorldstudiosWorldModBlocks.REBOUNDED_FIRE);
		MOLTEN_METAL = register("molten_metal", MoltenMetalItem::new);
		VERY_MOLTEN_METAL = register("very_molten_metal", VeryMoltenMetalItem::new);
		BLOCK_OF_FLINT = block(WorldstudiosWorldModBlocks.BLOCK_OF_FLINT);
		WARTED_EMERALD = register("warted_emerald", WartedEmeraldItem::new);
		WALKING_CHEST_SPAWN_EGG = register("walking_chest_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.WALKING_CHEST.get())));
		BRANITE = register("branite", BraniteItem::new);
		BRANITE_ORE = block(WorldstudiosWorldModBlocks.BRANITE_ORE, new Item.Properties().rarity(Rarity.UNCOMMON));
		BRANITE_LUNGE = register("branite_lunge", BraniteLungeItem::new);
		BULL_SPAWN_EGG = register("bull_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.BULL.get())));
		STONE_LUNGE = register("stone_lunge", StoneLungeItem::new);
		AMETHESIUM_ORE = block(WorldstudiosWorldModBlocks.AMETHESIUM_ORE, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant());
		AMETHESIUM_INGOT = register("amethesium_ingot", AmethesiumIngotItem::new);
		AMETHESIUM_PICKAXE = register("amethesium_pickaxe", AmethesiumPickaxeItem::new);
		AMETHESIUM_AXE = register("amethesium_axe", AmethesiumAxeItem::new);
		AMETHESIUM_SWORD = register("amethesium_sword", AmethesiumSwordItem::new);
		AMETHESIUM_SHOVEL = register("amethesium_shovel", AmethesiumShovelItem::new);
		AMETHESIUM_HOE = register("amethesium_hoe", AmethesiumHoeItem::new);
		AMETHESIUM_ARMOR_HELMET = register("amethesium_armor_helmet", AmethesiumArmorItem.Helmet::new);
		AMETHESIUM_ARMOR_CHESTPLATE = register("amethesium_armor_chestplate", AmethesiumArmorItem.Chestplate::new);
		AMETHESIUM_ARMOR_LEGGINGS = register("amethesium_armor_leggings", AmethesiumArmorItem.Leggings::new);
		AMETHESIUM_ARMOR_BOOTS = register("amethesium_armor_boots", AmethesiumArmorItem.Boots::new);
		AMETHESIUM_LUNGE = register("amethesium_lunge", AmethesiumLungeItem::new);
		CUBER_SPAWN_EGG = register("cuber_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.CUBER.get())));
		CUBE_ESSENCE = register("cube_essence", CubeEssenceItem::new);
		STEEL_BOAT = register("steel_boat", properties -> new BoatItem(WorldstudiosWorldModEntities.STEEL_BOAT.get(), properties.stacksTo(1)));
		CUTEPLANT = block(WorldstudiosWorldModBlocks.CUTEPLANT);
		CRAWLPING_SPAWN_EGG = register("crawlping_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.CRAWLPING.get())));
		SAWPING_SPAWN_EGG = register("sawping_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.SAWPING.get())));
		SOULDUST_LOG = block(WorldstudiosWorldModBlocks.SOULDUST_LOG);
		SOULDUST_WOOD = block(WorldstudiosWorldModBlocks.SOULDUST_WOOD);
		STRIPPED_SOULDUST_LOG = block(WorldstudiosWorldModBlocks.STRIPPED_SOULDUST_LOG);
		STRIPPED_SOULDUST_WOOD = block(WorldstudiosWorldModBlocks.STRIPPED_SOULDUST_WOOD);
		SOULDUST_PLANKS = block(WorldstudiosWorldModBlocks.SOULDUST_PLANKS);
		SOULDUST_LEAVES = block(WorldstudiosWorldModBlocks.SOULDUST_LEAVES);
		SOULDUST_STAIRS = block(WorldstudiosWorldModBlocks.SOULDUST_STAIRS);
		SOULDUST_SLAB = block(WorldstudiosWorldModBlocks.SOULDUST_SLAB);
		SOULDUST_FENCE = block(WorldstudiosWorldModBlocks.SOULDUST_FENCE);
		SOULDUST_FENCE_GATE = block(WorldstudiosWorldModBlocks.SOULDUST_FENCE_GATE);
		SOULDUST_DOOR = doubleBlock(WorldstudiosWorldModBlocks.SOULDUST_DOOR);
		SOULDUST_TRAPDOOR = block(WorldstudiosWorldModBlocks.SOULDUST_TRAPDOOR);
		SOULDUST_PRESSURE_PLATE = block(WorldstudiosWorldModBlocks.SOULDUST_PRESSURE_PLATE);
		SOULDUST_BUTTON = block(WorldstudiosWorldModBlocks.SOULDUST_BUTTON);
		SOULDUST_SIGN = signBlock(WorldstudiosWorldModBlocks.SOULDUST_SIGN, WorldstudiosWorldModBlocks.SOULDUST_WALL_SIGN, new Item.Properties().stacksTo(16));
		SOULDUST_HANGING_SIGN = hangingSignBlock(WorldstudiosWorldModBlocks.SOULDUST_HANGING_SIGN, WorldstudiosWorldModBlocks.SOULDUST_WALL_HANGING_SIGN, new Item.Properties().stacksTo(16));
		SOULDUST_BOAT = register("souldust_boat", properties -> new BoatItem(WorldstudiosWorldModEntities.SOULDUST_BOAT.get(), properties.stacksTo(1)));
		SOULDUST_CHEST_BOAT = register("souldust_chest_boat", properties -> new BoatItem(WorldstudiosWorldModEntities.SOULDUST_CHEST_BOAT.get(), properties.stacksTo(1)));
		SOULDUST_PICKAXE = register("souldust_pickaxe", SouldustPickaxeItem::new);
		SOULDUST_AXE = register("souldust_axe", SouldustAxeItem::new);
		SOULDUST_SWORD = register("souldust_sword", SouldustSwordItem::new);
		SOULDUST_SHOVEL = register("souldust_shovel", SouldustShovelItem::new);
		SOULDUST_HOE = register("souldust_hoe", SouldustHoeItem::new);
		GRAYSTONE = block(WorldstudiosWorldModBlocks.GRAYSTONE, new Item.Properties().rarity(Rarity.UNCOMMON));
		SKIP = register("skip", SkipItem::new);
		DUAL_WEED = doubleBlock(WorldstudiosWorldModBlocks.DUAL_WEED);
		DIRT_BOAT = register("dirt_boat", properties -> new BoatItem(WorldstudiosWorldModEntities.DIRT_BOAT.get(), properties.stacksTo(1)));
		BREAKABLE_BEDROCK = block(WorldstudiosWorldModBlocks.BREAKABLE_BEDROCK, new Item.Properties().rarity(Rarity.RARE));
		EYEFLOWER = block(WorldstudiosWorldModBlocks.EYEFLOWER, new Item.Properties().rarity(Rarity.RARE));
		SOULDUST_GRAVITE = block(WorldstudiosWorldModBlocks.SOULDUST_GRAVITE);
		OBSERVEER_SPAWN_EGG = register("observeer_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.OBSERVEER.get())));
		WOPPER_INGOT = register("wopper_ingot", WopperIngotItem::new);
		WOPPER_PICKAXE = register("wopper_pickaxe", WopperPickaxeItem::new);
		WOPPER_AXE = register("wopper_axe", WopperAxeItem::new);
		WOPPER_SWORD = register("wopper_sword", WopperSwordItem::new);
		WOPPER_SHOVEL = register("wopper_shovel", WopperShovelItem::new);
		WOPPER_HOE = register("wopper_hoe", WopperHoeItem::new);
		WOPPER_ARMOR_HELMET = register("wopper_armor_helmet", WopperArmorItem.Helmet::new);
		WOPPER_ARMOR_CHESTPLATE = register("wopper_armor_chestplate", WopperArmorItem.Chestplate::new);
		WOPPER_ARMOR_LEGGINGS = register("wopper_armor_leggings", WopperArmorItem.Leggings::new);
		WOPPER_ARMOR_BOOTS = register("wopper_armor_boots", WopperArmorItem.Boots::new);
		DIRT_CHEST = block(WorldstudiosWorldModBlocks.DIRT_CHEST);
		DARKENED_SAND = block(WorldstudiosWorldModBlocks.DARKENED_SAND);
		GIRTREE_LOG = block(WorldstudiosWorldModBlocks.GIRTREE_LOG);
		GIRTREE_WOOD = block(WorldstudiosWorldModBlocks.GIRTREE_WOOD);
		STRIPPED_GIRTREE_LOG = block(WorldstudiosWorldModBlocks.STRIPPED_GIRTREE_LOG);
		STRIPPED_GIRTREE_WOOD = block(WorldstudiosWorldModBlocks.STRIPPED_GIRTREE_WOOD);
		GIRTREE_PLANKS = block(WorldstudiosWorldModBlocks.GIRTREE_PLANKS);
		GIRTREE_LEAVES = block(WorldstudiosWorldModBlocks.GIRTREE_LEAVES);
		GIRTREE_STAIRS = block(WorldstudiosWorldModBlocks.GIRTREE_STAIRS);
		GIRTREE_SLAB = block(WorldstudiosWorldModBlocks.GIRTREE_SLAB);
		GIRTREE_FENCE = block(WorldstudiosWorldModBlocks.GIRTREE_FENCE);
		GIRTREE_FENCE_GATE = block(WorldstudiosWorldModBlocks.GIRTREE_FENCE_GATE);
		GIRTREE_DOOR = doubleBlock(WorldstudiosWorldModBlocks.GIRTREE_DOOR);
		GIRTREE_TRAPDOOR = block(WorldstudiosWorldModBlocks.GIRTREE_TRAPDOOR);
		GIRTREE_PRESSURE_PLATE = block(WorldstudiosWorldModBlocks.GIRTREE_PRESSURE_PLATE);
		GIRTREE_BUTTON = block(WorldstudiosWorldModBlocks.GIRTREE_BUTTON);
		GIRTREE_SIGN = signBlock(WorldstudiosWorldModBlocks.GIRTREE_SIGN, WorldstudiosWorldModBlocks.GIRTREE_WALL_SIGN, new Item.Properties().stacksTo(16));
		GIRTREE_HANGING_SIGN = hangingSignBlock(WorldstudiosWorldModBlocks.GIRTREE_HANGING_SIGN, WorldstudiosWorldModBlocks.GIRTREE_WALL_HANGING_SIGN, new Item.Properties().stacksTo(16));
		GIRTREE_BOAT = register("girtree_boat", properties -> new BoatItem(WorldstudiosWorldModEntities.GIRTREE_BOAT.get(), properties.stacksTo(1)));
		GIRTREE_CHEST_BOAT = register("girtree_chest_boat", properties -> new BoatItem(WorldstudiosWorldModEntities.GIRTREE_CHEST_BOAT.get(), properties.stacksTo(1)));
		DIRTY_WATER_BUCKET = register("dirty_water_bucket", DirtyWaterItem::new);
		SOGGY_DARKENED_SAND = block(WorldstudiosWorldModBlocks.SOGGY_DARKENED_SAND);
		WANDERER_SPAWN_EGG = register("wanderer_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.WANDERER.get())));
		DRIED_FLESH = register("dried_flesh", DriedFleshItem::new);
		GIRSTONE = block(WorldstudiosWorldModBlocks.GIRSTONE);
		IRON_UPGRADE_SMITHING_TEMPLATE = register("iron_upgrade_smithing_template", IronUpgradeSmithingTemplateItem::new);
		TRAVERTINE = block(WorldstudiosWorldModBlocks.TRAVERTINE);
		TALLMOSS = block(WorldstudiosWorldModBlocks.TALLMOSS);
		CHEAP_POINT = block(WorldstudiosWorldModBlocks.CHEAP_POINT);
		PLANT_FOOD = register("plant_food", PlantFoodItem::new);
		DIRT_SHIELD = register("dirt_shield", DirtShieldItem::new);
		REPAIRER = register("repairer", RepairerItem::new);
		IRON_LUNGE = register("iron_lunge", IronLungeItem::new);
		DIAMOND_LUNGE = register("diamond_lunge", DiamondLungeItem::new);
		NETHERITE_LUNGE = register("netherite_lunge", NetheriteLungeItem::new);
		URAINIUM_LUNGE = register("urainium_lunge", UrainiumLungeItem::new);
		TITAN_LUNGE = register("titan_lunge", TitanLungeItem::new);
		SPARKLE_LUNGE = register("sparkle_lunge", SparkleLungeItem::new);
		BLAZITE_LUNGE = register("blazite_lunge", BlaziteLungeItem::new);
		WOOL_LUNGE = register("wool_lunge", WoolLungeItem::new);
		IGNIGHTIUM_LUNGE = register("ignightium_lunge", IgnightiumLungeItem::new);
		REPEATING_COMMAND_BLOCK_LUNGE = register("repeating_command_block_lunge", RepeatingCommandBlockLungeItem::new);
		STEEL_LUNGE = register("steel_lunge", SteelLungeItem::new);
		WOPPER_LUNGE = register("wopper_lunge", WopperLungeItem::new);
		STEEL_SYTHE = register("steel_sythe", SteelSytheItem::new);
		TRASHERRACK = block(WorldstudiosWorldModBlocks.TRASHERRACK);
		TRASH_BRUTE_SPAWN_EGG = register("trash_brute_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(WorldstudiosWorldModEntities.TRASH_BRUTE.get())));
		END_NEZIUM_ORE = block(WorldstudiosWorldModBlocks.END_NEZIUM_ORE, new Item.Properties().rarity(Rarity.UNCOMMON));
		RAW_NEZIUM = register("raw_nezium", RawNeziumItem::new);
		NEZIUM_INGOT = register("nezium_ingot", NeziumIngotItem::new);
		NEZIUM_PICKAXE = register("nezium_pickaxe", NeziumPickaxeItem::new);
		NEZIUM_AXE = register("nezium_axe", NeziumAxeItem::new);
		NEZIUM_SWORD = register("nezium_sword", NeziumSwordItem::new);
		NEZIUM_SHOVEL = register("nezium_shovel", NeziumShovelItem::new);
		NEZIUM_HOE = register("nezium_hoe", NeziumHoeItem::new);
		NEZIUM_ARMOR_HELMET = register("nezium_armor_helmet", NeziumArmorItem.Helmet::new);
		NEZIUM_ARMOR_CHESTPLATE = register("nezium_armor_chestplate", NeziumArmorItem.Chestplate::new);
		NEZIUM_ARMOR_LEGGINGS = register("nezium_armor_leggings", NeziumArmorItem.Leggings::new);
		NEZIUM_ARMOR_BOOTS = register("nezium_armor_boots", NeziumArmorItem.Boots::new);
		NEZIUM_LUNGE = register("nezium_lunge", NeziumLungeItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, Item.Properties::new);
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), () -> properties);
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new DoubleHighBlockItem(block.get(), prop), () -> properties);
	}

	private static DeferredItem<Item> signBlock(DeferredHolder<Block, Block> block, DeferredHolder<Block, Block> wallBlock) {
		return signBlock(block, wallBlock, new Item.Properties());
	}

	private static DeferredItem<Item> signBlock(DeferredHolder<Block, Block> block, DeferredHolder<Block, Block> wallBlock, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new SignItem(block.get(), wallBlock.get(), prop), () -> properties);
	}

	private static DeferredItem<Item> hangingSignBlock(DeferredHolder<Block, Block> block, DeferredHolder<Block, Block> wallBlock) {
		return hangingSignBlock(block, wallBlock, new Item.Properties());
	}

	private static DeferredItem<Item> hangingSignBlock(DeferredHolder<Block, Block> block, DeferredHolder<Block, Block> wallBlock, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new HangingSignItem(block.get(), wallBlock.get(), prop), () -> properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.Item.ITEM, (stack, access) -> new TrashBagInventoryCapability(access), TRASH_BAG.get());
		event.registerItem(Capabilities.Fluid.ITEM, (stack, access) -> new BucketResourceHandler(access), ACID_FLUID_BUCKET.get());
		event.registerItem(Capabilities.Fluid.ITEM, (stack, access) -> new BucketResourceHandler(access), BRAIN_FLUID_BUCKET.get());
		event.registerItem(Capabilities.Fluid.ITEM, (stack, access) -> new BucketResourceHandler(access), DIRTY_WATER_BUCKET.get());
	}
}