modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="worldstudios_world"
version="26.1.2.8.4"
displayName="WorldStudios World"
displayURL="https://its99studios.wordpress.com"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="WorldStudios"
description="Adds a bunch of random stuff to minecraft java like an ender helmet and a biome full of waste."
enumExtensions="META-INF/enumextensions.json"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "worldstudios_world.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.worldstudios_world]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.worldstudios_world]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration